{% set name = "tango-gateway" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tango-gateway-{{ version }}.tar.gz
  sha256: 58fc8d32e9364882f96ee46d93ca45e9f6b158f913ec9e555f9fd4d660c54244

build:
  entry_points:
    - tango-gateway = tangogateway:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools-scm
  run:
    - aiozmq
    - python >=3.4

test:
  imports:
    - tangogateway
  commands:
    - pip check
    - tango-gateway --help
  requires:
    - pip

about:
  home: https://gitlab.com/MaxIV/tango-gateway
  summary: A Tango gateway server
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - initfve
    - beenje
