schema_version: 1

context:
  name: tango-gateway
  version: 1.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tango_gateway-${{ version }}.tar.gz
  sha256: 6b983e82dabc06ed78650550ba7945ecf2e55aec5b8e8e1ac691a4211952dab0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - tango-gateway = tangogateway:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
  run:
    - pyzmq
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - tangogateway
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - tango-gateway --help
    requirements:
      run:
        - python ${{ python_min }}.*
  - script:
      - tango-gateway --help

about:
  summary: A Tango gateway server
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  homepage: https://gitlab.com/MaxIV/tango-gateway

extra:
  recipe-maintainers:
    - initfve
    - beenje
